Repository fit-ctu-discord/honza-botner, pull requests merged in 2021-11, with the labels that each got.

#247 Upgrade to .NET 6.0 and centralize packages versions
  .github/workflows/dotnet-core.yml
  Directory.Build.props
  Directory.Build.targets
  Packages.props
  global.json
  src/HonzaBotner.Database/HonzaBotner.Database.csproj
  src/HonzaBotner.Discord.Services/HonzaBotner.Discord.Services.csproj
  src/HonzaBotner.Discord/HonzaBotner.Discord.csproj
  src/HonzaBotner.Services.Contract/HonzaBotner.Services.Contract.csproj
  src/HonzaBotner.Services.Test/HonzaBotner.Services.Test.csproj
  src/HonzaBotner.Services/EmojiCounterService.cs
  src/HonzaBotner.Services/HonzaBotner.Services.csproj
  src/HonzaBotner.Services/RemindersService.cs
  src/HonzaBotner.Services/RoleBindingsService.cs
  src/HonzaBotner.Services/WarningService.cs
  src/HonzaBotner/Controllers/AuthController.cs
  src/HonzaBotner/Controllers/ErrorController.cs
  src/HonzaBotner/HonzaBotner.csproj
Labels: release: dependencies

#246 Use automatic generation in Releases in favor of duplicating CHANGELOG+Releases
  .github/release.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: release: ignore

#252 Replace Hangfire with custom CRON job runner
  .gitignore
  HonzaBotner.sln
  Packages.props
  src/HonzaBotner.Database/CountedEmoji.cs
  src/HonzaBotner.Discord.Services/Commands/ReminderCommands.cs
  src/HonzaBotner.Discord.Services/Extensions/CommandContextExtensions.cs
  src/HonzaBotner.Discord.Services/HonzaBotner.Discord.Services.csproj
  src/HonzaBotner.Discord.Services/Jobs/TriggerRemindersJobProvider.cs
  src/HonzaBotner.Discord/Extensions/DiscordExtensions.cs
  src/HonzaBotner.Scheduler/Contract/CronAttribute.cs
  src/HonzaBotner.Scheduler/Contract/ICronJob.cs
  src/HonzaBotner.Scheduler/Contract/IJob.cs
  src/HonzaBotner.Scheduler/CronJobWrapper.cs
  src/HonzaBotner.Scheduler/HonzaBotner.Scheduler.csproj
  src/HonzaBotner.Scheduler/InvalidConfigurationException.cs
  src/HonzaBotner.Scheduler/SchedulerHostedService.cs
  src/HonzaBotner.Scheduler/ScopedSchedulerJobWrapper.cs
  src/HonzaBotner.Scheduler/StartupExtensions.cs
  src/HonzaBotner.Services.Contract/Dto/EmojiCount.cs
  src/HonzaBotner.Services.Contract/HonzaBotner.Services.Contract.csproj
  src/HonzaBotner.Services.Contract/IRecurringJobProvider.cs
  src/HonzaBotner.Services.Test/HashServiceTest.cs
  src/HonzaBotner.Services.Test/HonzaBotner.Services.Test.csproj
  src/HonzaBotner.Services/HonzaBotner.Services.csproj
  src/HonzaBotner.Services/RemindersService.cs
  src/HonzaBotner/HonzaBotner.csproj
  src/HonzaBotner/Startup.cs
  src/HonzaBotner/appsettings.json
Labels: release: changed
