Repository fit-ctu-discord/honza-botner, pull requests merged in 2022-02, with the labels that each got.

#275 Rewrite polls, introduce Add command to modify existing Abc polls
  src/HonzaBotner.Discord.Services/Commands/PinCommands.cs
  src/HonzaBotner.Discord.Services/Commands/PollCommands.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/AbcPoll.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/IPoll.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/Poll.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/YesNoPoll.cs
  src/HonzaBotner.Discord.Services/EventHandlers/PollReactionsHandler.cs
  src/HonzaBotner.Discord/EventHandler/EventHandlersListBuilder.cs
  src/HonzaBotner.Discord/EventHandler/IEventHandler.cs
  src/HonzaBotner/Startup.cs
Labels: release: changed

#293 Teachers can count members now
  docs/features/member.md
  src/HonzaBotner.Discord.Services/Attributes/CustomBaseAttribute.cs
  src/HonzaBotner.Discord.Services/Attributes/RequireAllowlistAttribute.cs
  src/HonzaBotner.Discord.Services/Attributes/RequireModAttribute.cs
  src/HonzaBotner.Discord.Services/Commands/MemberCommands.cs
  src/HonzaBotner.Discord.Services/Options/CommandAllowlistsOptions.cs
  src/HonzaBotner.Discord.Services/Options/CommonCommandOptions.cs
  src/HonzaBotner.Discord.Services/ServiceCollectionExtensions.cs
  src/HonzaBotner.Discord/Attributes/ICustomAttribute.cs
  src/HonzaBotner.Discord/Attributes/IRequireModAttribute.cs
  src/HonzaBotner.Discord/DiscordBot.cs
  src/HonzaBotner/appsettings.BotDev.json
  src/HonzaBotner/appsettings.CvutFit.json
  src/HonzaBotner/appsettings.Development.json
Labels: release: changed

#297 Announce member info
  src/HonzaBotner.Discord.Services/Commands/MemberCommands.cs
Labels: release: added

#305 Fix localization of verification button
  src/HonzaBotner.Discord.Services/EventHandlers/VerificationEventHandler.cs
Labels: release: fixed

#306 Fix reminders not including everyone
  src/HonzaBotner.Discord.Services/Jobs/TriggerRemindersJobProvider.cs
Labels: release: fixed
