Repository fit-ctu-discord/honza-botner, pull requests merged in 2022-05, with the labels that each got.

#339 Fix escaped mentions
  src/HonzaBotner.Discord.Services/Commands/FunCommands.cs
  src/HonzaBotner.Discord.Services/Commands/ReminderCommands.cs
  src/HonzaBotner.Discord.Services/Commands/WarningCommands.cs
  src/HonzaBotner.Discord.Services/Extensions/StringExtensions.cs
  src/HonzaBotner.Discord.Services/Jobs/TriggerRemindersJobProvider.cs
  src/HonzaBotner.Discord.Services/Managers/ReminderManager.cs
Labels: release: fixed

#330 Improvements in the Sha256HashService
  src/HonzaBotner.Services/Sha256HashService.cs
Labels: release: changed

#340 Change reaction's handling on poll messages
  src/HonzaBotner.Discord.Services/Commands/PollCommands.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/AbcPoll.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/Poll.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/PollException.cs
  src/HonzaBotner.Discord.Services/Commands/Polls/YesNoPoll.cs
  src/HonzaBotner.Discord.Services/EventHandlers/PollReactionsHandler.cs
  src/HonzaBotner/Startup.cs
Labels: release: changed

#342 StandUps
  src/HonzaBotner.Discord.Services/Helpers/StandUpStats.cs
  src/HonzaBotner.Discord.Services/Jobs/StandUpJobProvider.cs
  src/HonzaBotner.Discord.Services/Jobs/TriggerRemindersJobProvider.cs
  src/HonzaBotner.Discord.Services/Options/CommonCommandOptions.cs
  src/HonzaBotner.Scheduler/SchedulerHostedService.cs
  src/HonzaBotner/Startup.cs
  src/HonzaBotner/appsettings.BotDev.json
  src/HonzaBotner/appsettings.CvutFit.json
  src/HonzaBotner/appsettings.Development.json
Labels: release: added

#347 Make checklist syntax consistent with Markdown
  src/HonzaBotner.Discord.Services/Jobs/StandUpJobProvider.cs
Labels: release: changed
