Repository fit-ctu-discord/honza-botner, pull requests merged in 2022-09, with the labels that each got.

#357 Synchronize changes in hotfix version 2022.3.1
  Directory.Build.props
  src/HonzaBotner.Discord.Services/Jobs/StandUpJobProvider.cs
Labels: priority, release: ignore

#371 Add academic senate role to badge roles
  src/HonzaBotner/appsettings.CvutFit.json
Labels: release: ignore

#377 The council (seznamka Chads) will decide your fate ️‍🔥️‍
  src/HonzaBotner.Discord.Services/EventHandlers/RoleBindingsHandler.cs
  src/HonzaBotner.Discord.Services/Options/RolesOptions.cs
  src/HonzaBotner.Discord.Services/ServiceCollectionExtensions.cs
  src/HonzaBotner/appsettings.BotDev.json
  src/HonzaBotner/appsettings.CvutFit.json
Labels: invalid, release: ignore

#376 More detailed how to
  docs/howto.md
Labels: documentation, release: changed

#379 Revert "The council (seznamka Chads) will decide your fate ️‍🔥️‍"
  src/HonzaBotner.Discord.Services/EventHandlers/RoleBindingsHandler.cs
  src/HonzaBotner.Discord.Services/Options/RolesOptions.cs
  src/HonzaBotner.Discord.Services/ServiceCollectionExtensions.cs
  src/HonzaBotner/appsettings.BotDev.json
  src/HonzaBotner/appsettings.CvutFit.json
Labels: release: ignore

#317 Slash commands
  Packages.props
  docker-compose.yml
  src/HonzaBotner.Database/NewsConfig.cs
  src/HonzaBotner.Discord.Services/Attributes/CustomBaseAttribute.cs
  src/HonzaBotner.Discord.Services/Attributes/RequireAllowlistAttribute.cs
  src/HonzaBotner.Discord.Services/Attributes/RequireModAttribute.cs
  src/HonzaBotner.Discord.Services/Commands/AuthorizeCommands.cs
  src/HonzaBotner.Discord.Services/Commands/BotCommands.cs
  src/HonzaBotner.Discord.Services/Commands/ChannelCommands.cs
  src/HonzaBotner.Discord.Services/Commands/EmoteCommands.cs
  src/HonzaBotner.Discord.Services/Commands/FunCommands.cs
  src/HonzaBotner.Discord.Services/Commands/MemberCommands.cs
  src/HonzaBotner.Discord.Services/Commands/MessageCommands.cs
  src/HonzaBotner.Discord.Services/Commands/ModerationCommands.cs
  src/HonzaBotner.Discord.Services/Commands/NewsManagementCommands.cs
  src/HonzaBotner.Discord.Services/Commands/PinCommands.cs
  src/HonzaBotner.Discord.Services/Commands/PollCommands.cs
  src/HonzaBotner.Discord.Services/Commands/ReminderCommands.cs
  src/HonzaBotner.Discord.Services/Commands/TestCommands.cs
  src/HonzaBotner.Discord.Services/Commands/VoiceCommands.cs
  src/HonzaBotner.Discord.Services/Commands/WarningCommands.cs
  src/HonzaBotner.Discord.Services/EventHandlers/ThreadHandler.cs
  src/HonzaBotner.Discord.Services/Extensions/CommandContextExtensions.cs
  src/HonzaBotner.Discord.Services/Jobs/NewsJobProvider.cs
  src/HonzaBotner.Discord.Services/Managers/VoiceManager.cs
  src/HonzaBotner.Discord.Services/Options/CommandAllowlistsOptions.cs
  src/HonzaBotner.Discord.Services/Options/CommonCommandOptions.cs
  src/HonzaBotner.Discord.Services/Options/CustomVoiceOptions.cs
  src/HonzaBotner.Discord.Services/ServiceCollectionExtensions.cs
  src/HonzaBotner.Discord/CommandsConfigurator.cs
  src/HonzaBotner.Discord/ConfigGuildProvider.cs
  src/HonzaBotner.Discord/DiscordBot.cs
  src/HonzaBotner.Discord/DiscordConfig.cs
  src/HonzaBotner.Discord/DiscordHelper.cs
  src/HonzaBotner.Discord/DiscordWrapper.cs
  src/HonzaBotner.Discord/HonzaBotner.Discord.csproj
  src/HonzaBotner.Discord/ICommandConfigurator.cs
  src/HonzaBotner.Discord/IGuildProvider.cs
  src/HonzaBotner.Discord/Managers/IVoiceManager.cs
  src/HonzaBotner.Discord/ServiceCollectionExtensions.cs
  src/HonzaBotner.Services.Contract/INewsConfigService.cs
  src/HonzaBotner.Services.Contract/NewsConfigHelper.cs
  src/HonzaBotner.Services/NewsConfigService.cs
  src/HonzaBotner/Startup.cs
  src/HonzaBotner/appsettings.BotDev.json
  src/HonzaBotner/appsettings.CvutFit.json
  src/HonzaBotner/appsettings.Development.json
Labels: release: changed

#393 🐛 Change news job period and fix run-once command
  src/HonzaBotner.Discord.Services/Commands/NewsManagementCommands.cs
  src/HonzaBotner.Discord.Services/Jobs/NewsJobProvider.cs
Labels: release: changed

#395 🚑️ News interval
  src/HonzaBotner.Discord.Services/Jobs/NewsJobProvider.cs
Labels: release: changed
