Repository fit-ctu-discord/honza-botner, pull requests merged in 2022-12, with the labels that each got.

#440 Update DSharpPlus
  Packages.props
  src/HonzaBotner.Discord.Services/EventHandlers/Helpers/WelcomeMessageHandler.cs
Labels: dependencies

#441 Allow opt-in ping in standup
  src/HonzaBotner.Discord.Services/EventHandlers/StandupButtonHandler.cs
  src/HonzaBotner.Discord.Services/Jobs/StandUpJobProvider.cs
  src/HonzaBotner.Discord.Services/Options/ButtonOptions.cs
  src/HonzaBotner/Startup.cs
  src/HonzaBotner/appsettings.BotDev.json
  src/HonzaBotner/appsettings.CvutFit.json
  src/HonzaBotner/appsettings.Development.json
Labels: release: added

#394 ⬆️ Upgrade .NET to 7.0
  .github/workflows/dotnet-core.yml
  .github/workflows/releases.yml
  Directory.Build.props
  Packages.props
  global.json
Labels: on hold, release: dependencies

#455 Allow moderators to cancel reminders
  src/HonzaBotner.Discord.Services/EventHandlers/ReminderReactionsHandler.cs
Labels: release: changed

#454 Dependency management: Switch to CPM
  Directory.Build.props
  Directory.Packages.props
  HonzaBotner.sln
  Packages.props
Labels: priority, release: changed

#471 Minor fixes
  src/HonzaBotner.Discord.Services/Commands/BotCommands.cs
  src/HonzaBotner.Discord.Services/Commands/MemberCommands.cs
  src/HonzaBotner/appsettings.Development.json
Labels: release: fixed
